hsi_folder: '/mnt/hdd1/datasets/hyperspectral/hyper_penguin/HSpenguins/images/HS'
binary_type: '.nh9'

mask_anotation_json: '/mnt/hdd1/datasets/hyperspectral/hyper_penguin/HSpenguins/anotation/mask_images/mask_images.json'
mask_folder: '/mnt/hdd1/datasets/hyperspectral/hyper_penguin/HSpenguins/anotation/mask_images'

reference_id_data: '/mnt/hdd1/datasets/hyperspectral/hyper_penguin/HSpenguins/anotation/penguinID_information.json'
classwize_data_num: 30000
select_target: 10

save_folder: '/mnt/hdd1/datasets/hyperspectral/hyper_penguin/pixelwisePenguinIdDataset'
save_file_name: 'white_5mean_10pen'

mask_image: 'white'

train_rate: 0.8
random_seed: 0

blur: Null
mean: 5