batch_size: 128
train_parameter:
  epochs: 300
  lr: 0.001
  scheduler_gamma: 0.6

# model
input_dim: 151
output_dim: 10
dropout_prob: 0.5

# device
device: 'cuda:0'

model_path: 'runs/<date>/<time>/weight.pt'

